spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.4.35:3306/liuliangmybatis
    username: mybatis
    password: mybatis%2022
mybatis-plus:
  global-config:
    db-config:
      table-prefix: platform_
#