logging:
  pattern:
    console: "%d %clr(%5p)  --- [%16t] %clr(%-40.40c){cyan} : %m %n"
  file:
    name: console.log
  logback:
    rollingpolicy:
      max-file-size: 4KB
      file-name-pattern: console.%d{yyyy-mm-dd}.%i.log
